# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udio_control.proto\x12\x05\x61udio\"0\n\nAudioChunk\x12\r\n\x05pcm16\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"\x19\n\x08TTSChunk\x12\r\n\x05pcm16\x18\x01 \x01(\x0c\x32?\n\x07\x41udioIO\x12\x34\n\x08\x43onverse\x12\x11.audio.AudioChunk\x1a\x0f.audio.TTSChunk\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=30
  _globals['_AUDIOCHUNK']._serialized_end=78
  _globals['_TTSCHUNK']._serialized_start=80
  _globals['_TTSCHUNK']._serialized_end=105
  _globals['_AUDIOIO']._serialized_start=107
  _globals['_AUDIOIO']._serialized_end=170
# @@protoc_insertion_point(module_scope)
